import type { LogoGenerationParams } from "@/types/logo";
import type { ProductDesignCandidate, ProductViewType } from "@/types/product-design";
import type { MarketingImageParams, ImageType } from "@/types/marketing-image";
import type { DesignBrief } from "@/types/design-brief";
import { resolveProductInformationCompleteness } from "@/services/product-information-completeness";

const logoTypePrompts={wordmark:"wordmark: use the full brand name as the primary typographic logo",lettermark:"lettermark: use a concise brand-initial monogram",pictorial:"pictorial mark: use one recognizable concrete symbol",abstract:"abstract mark: use an original non-representational geometric symbol",combination:"combination mark: combine a distinct symbol with the brand name",emblem:"emblem mark: place the brand name within a contained badge silhouette"} as const;
const fontPrompts={serif:"elegant classic serif typography",sans:"modern rational sans-serif typography",handwritten:"warm natural handwritten typography"} as const;
export const logoTypeForIndex=(params:LogoGenerationParams,index:number)=>{const fallback=["wordmark","lettermark","pictorial","abstract","combination","emblem"] as const;const types=params.logoTypes?.length?params.logoTypes:fallback;return types[index%types.length];};
export function buildLogoPrompt(params: LogoGenerationParams, index: number) {
  const brief=params.brief; const monogram=(brief.brand.name||"B").replace(/\s+/g,"").slice(0,2).toUpperCase();
  const logoType=logoTypeForIndex(params,index);const weight=Math.max(1,Math.min(5,params.fontWeight||3));const font=params.fontStyle?fontPrompts[params.fontStyle]:"typography inferred from the brand personality";const color=params.colorPreference?.trim()?`Required color direction: ${params.colorPreference.trim()}.`:"Derive a restrained color palette from the brand personality.";const avoid=params.avoidElements?.trim()?`STRICT NEGATIVE CONSTRAINT: no ${params.avoidElements.trim()}, do not depict or imply these elements.`:"";
  return `Professional flat vector logo design for ${brief.brand.name}, a ${brief.brand.positioning}. Required logo category: ${logoTypePrompts[logoType]}. Industry: ${brief.product.industry}, category: ${brief.product.category}. Brand personality: ${brief.brand.personality.join(", ")}. Typography: ${font}; font weight level ${weight}/5 (${weight<=2?"thin and refined":weight>=4?"bold and powerful":"balanced medium"}). ${color} ${avoid} ${params.styleHint||""} ${params.baseLogoId?`Create a variation based on the selected direction: ${params.styleHint||"refined evolution"}.`:""} Concept option ${index+1}, distinctive silhouette, balanced negative space, scalable brand mark, flat vector colors, clean white background. Use monogram ${monogram} only for a lettermark; use the exact brand name only where the selected category requires text. No unrelated words, no packaging mockup, no 3D scene, no watermark.`;
}
export function buildProductViewPrompt(candidate: ProductDesignCandidate, view:ProductViewType, brand:string, product:string, variation?:string){
  const viewLabel={front:"FRONT VIEW, straight-on camera, product face parallel to camera",side:"SIDE VIEW, exact 90-degree rotation from the front",back:"BACK VIEW, exact 180-degree rotation from the front"}[view];
  const facePurpose={front:"Create a strong visual hierarchy with an intentionally blank central typography zone.",side:"Continue the same pattern and color blocking around the side surface; keep it completely typographic-free.",back:"Create restrained visual structure and several intentionally blank information zones for later typesetting."}[view];
  const allKnownTexts=[brand,product,...(candidate.copyLayout||[]).map(item=>item.displayText),...(candidate.copyApplied||[]).map(item=>item.content)].filter(Boolean);
  const viewSafeDirection=allKnownTexts.reduce((text,value)=>text.split(value).join("[reserved typography area]"),candidate.generationPrompt||"Design a coherent premium surface system with color blocking and original pattern language.");
  const formDescription=candidate.containerType.id==="ai-auto-form"?"Infer and design the most appropriate production-believable physical form from the confirmed category and use case; do not default to unrelated cosmetic bottles or jars.":`Mandatory product form: ${candidate.containerType.volume} ${candidate.containerType.name}; interaction or access method: ${candidate.containerType.dispensingType}; structure description: ${candidate.containerType.description||"preserve the confirmed product form"}.`;
  return `ONE complete consumer product only. ${viewLabel}. Never render the supplied brand or product name; use only the physical-form description. ${formDescription} ${candidate.containerType.kind==="solid_product"?"This is a solid finished product, NOT a bottle, jar, tube or cosmetic container.":"Preserve the exact physical silhouette, seal, cap, proportions and construction."} Style: ${candidate.styleDirection}. Material: ${candidate.cmf.material}. Colors: ${candidate.cmf.colorScheme.join(", ")}. Finish: ${candidate.cmf.finish}. ${viewSafeDirection} ${facePurpose} ${variation||""} ABSOLUTE TYPOGRAPHY BAN: no logo, no brand name, no product name, no slogan, no words, no letters, no numbers, no ingredient table, no icons that resemble letters, no pseudo-text and no label placeholder marks. Leave clean uninterrupted surface areas for a later professional typography layer. The entire product must be visible from top edge to bottom edge with 12 percent empty margin on every side, centered, upright, same scale, isolated on a plain warm-white studio background. No crop, no close-up, no perspective angle, no hands, no props, no outer box, no second product, no collage, no moodboard, no presentation board, no diagrams, no UI, no annotation, no watermark.`;
}
export function buildProductHeroPrompt(candidate:ProductDesignCandidate,brief:DesignBrief,variation?:string){
  const isHeroCopy=(item:NonNullable<ProductDesignCandidate["copyLayout"]>[number])=>item.enabled&&item.face==="front"&&(item.role==="brand"||item.role==="product_name"||item.sourceKey==="main_slogan");
  const exactCopy=(candidate.copyLayout||[]).filter(isHeroCopy).map(item=>item.displayText).filter(Boolean).slice(0,3);
  const scenario=brief.product.usageScenarios||brief.consumer.keywords.join(", ")||"a refined real-life environment appropriate for this product category";
  const formRule=candidate.containerType.kind==="solid_product"?"This is a finished solid product, not cosmetic packaging. Show its real controls, ports, openings and functional construction clearly.":candidate.containerType.kind==="flexible_pack"?"Show the complete flexible package with realistic seals, folds and material thickness.":"Show the complete primary product container with realistic closure, dispensing structure and material thickness.";
  const excludedTexts=(candidate.copyLayout||[]).filter(item=>item.enabled&&!isHeroCopy(item)&&item.displayText).map(item=>item.displayText);
  const heroDirection=excludedTexts.reduce((text,value)=>text.split(value).join("[detailed copy omitted from hero scene]"),candidate.generationPrompt||"Build a sophisticated integrated surface graphic system using controlled color blocking, original illustration or pattern language, tactile material grain, realistic highlights, micro shadows and production-believable details.");
  return `HIGH-END COMMERCIAL PRODUCT DESIGN PHOTOGRAPHY, editorial advertising quality comparable to a premium brand campaign. Create one coherent portrait hero image, not a design board. Main subject: the complete ${brief.brand.name} ${brief.product.name}, confirmed form ${candidate.containerType.volume} ${candidate.containerType.name}. ${formRule} Preserve the exact silhouette, proportions and surface design from the reference image. Three-quarter front view, entire product fully visible from top to bottom with generous breathing room, no cropping. Style direction: ${candidate.styleDirection}. CMF: ${candidate.cmf.colorScheme.join(", ")}; ${candidate.cmf.material}; ${candidate.cmf.finish}. ${heroDirection} Scene: ${scenario}. Use tasteful category-relevant props and a softly blurred premium environment, but never cover the product. Warm natural editorial lighting, shallow depth of field, physically realistic materials, sharp hero product, 85mm commercial photography, premium art direction. ${exactCopy.length?`If any readable typography appears, use only these exact supplied strings: ${[brief.brand.name,brief.product.name,...exactCopy].join(" | ")}. Do not invent words.`:"No invented words or random lettering."} ${variation||""} One complete hero composition only. No orthographic sheet, no front-side-back lineup, no collage, no moodboard, no UI, no annotations, no floating labels, no white information cards, no technical diagram, no watermark.`;
}
export function buildProductDirectPrompt(candidate:ProductDesignCandidate,brief:DesignBrief,variation?:string){
  const completeness=resolveProductInformationCompleteness(brief,candidate.containerType);
  const visualDirection=(candidate.generationPrompt||"建立完整、成熟且可生产的产品视觉系统。")
    .replace(/(?:背面信息|功效说明|成分说明|使用说明|主标语|副标语|产品名称|品牌名称|copyAdaptations|sourceKey)\s*[：:]/g,"");
  const structure=candidate.containerType.id==="ai-auto-form"?`根据“${brief.product.category}”和产品用途推导合理、可生产的真实产品形态，禁止套用无关瓶罐。`:`严格保持第 1 张参考图中的${candidate.containerType.volume} ${candidate.containerType.name}轮廓、比例、封口、结构、使用方式和基础包材，不得因视觉设计改变尺寸和结构。`;
  const snapshot=candidate.directionSnapshot;
  const views=candidate.viewMode==="two_view"?"同一产品的完整正面与完整背面，两视图并列且不得出现侧面栏":"同一产品的完整正面、完整侧面与完整背面，三视图比例严格一致";
  const layoutRule=`固定上下两段版式。上方严格占画面 60%，必须是一张连续、完整、不被任何边框或子视窗切割的商业场景主画面；下方严格占画面 40%，必须是独立、干净、统一背景的产品结构展示区，横向整齐排列${views}，所有视图同尺度、同基线、完整不裁切。上下仅使用一条水平视觉分界。严禁左右分栏、竖向切割、斜切分区、自由拼贴、视图嵌入、画中画、重复场景、上下位置互换。`;
  const typography=snapshot?.typographySystem;
  const typographyRule=typography?`字体系统：${typography.fontPairing}。层级要求：品牌 ${typography.hierarchy.brand}；品名 ${typography.hierarchy.productName}；标语 ${typography.hierarchy.slogan}；短卖点 ${typography.hierarchy.supporting}；背面正文 ${typography.hierarchy.body}。对齐：${typography.alignment}。间距节奏：${typography.spacing}。网格：${typography.grid}。图文融合：${typography.graphicIntegration}。`:"字体系统最多使用两套字体，至少形成品牌/品名、标语、辅助信息三级清晰层级；通过字号、字重、字距、行距和主对齐轴建立节奏，禁止全部同字号、同字重、机械居中堆叠。";
  const direction=snapshot?`核心创意：${snapshot.creativeConcept||candidate.styleDirection}。视觉性格：${snapshot.visualPersonality||"按当前方向执行"}。设计取舍：${snapshot.designRationale||"保持结构，开放视觉"}。图形语言：${snapshot.surfaceCmf?.graphicLanguage||snapshot.graphicLanguage}。${typographyRule}表面工艺：${snapshot.surfaceCmf?.printFinish||snapshot.materialStrategy}。商业场景：${snapshot.surfaceCmf?.sceneDirection||snapshot.sceneDirection}。本方向禁用：${snapshot.avoidMotifs.join("、")||"仅禁止无关产品、乱码、UI 和水印"}。`:typographyRule;
  return `直接生成一张完整的专业商业产品概念设计图，所有包装文字、字体层级与整体视觉由图像模型一次完成。
产品背景：${brief.product.name}；品类：${brief.product.category}。这些只用于理解产品，不要求作为固定包装文案。${structure}
参考图输入顺序：第 1 张是器型/结构硬约束；第 2 张是不可改动的定稿 Logo 强参考；如有第 3 张则是本方向可选择吸收的视觉参考板。
必须忠实复现第 2 张定稿 Logo 的图形、字形、比例、留白和组合关系，在场景产品与下方结构视图中保持一致；不得重新设计、重新打字、替换、省略或加入其他 Logo。视觉参考图只借鉴气质，不能覆盖定稿 Logo。
【9:16固定画面构图】${layoutRule} 上方场景中的产品与下方结构视图必须使用完全一致的器型、配色、图案、品牌标志、可见文案和字体系统。场景产品只能出现一次并完整可见；下方仅展示结构视图，不得重复场景。商业场景像正式品牌广告摄影，材质可信、光影自然、使用语境明确。
设计方向：${candidate.styleDirection}。${direction}基础包材：${candidate.cmf.material}；方向色板：${candidate.cmf.colors?.map(item=>`${item.name}${item.hex}`).join("、")||candidate.cmf.colorScheme.join("、")}；表面处理：${candidate.cmf.finish}。
${visualDirection}
除定稿 Logo 外，包装上的所有可见文字由 AI 自由创作：可决定内容、语言、数量、字体组合、字号、字重、字距、对齐和图文关系，不读取或复述第 3 步文案，也不要求内容事实准确，但视觉信息架构必须完整。当前产品的信息完整度规则：${completeness.promptRule} 文字必须像成熟品牌包装的一部分，最多两套字体，至少形成主标识、核心信息、辅助文字三级视觉层级，并与图形、色块、留白和材质自然融合。禁止普通办公文档式排版、所有文字同字号居中堆叠、乱码式大段文字。不得出现“背面信息、功效说明、成分说明、使用说明”等系统字段名，也不得出现 sourceKey、copyAdaptations、提示词、JSON、UI 或后台术语。文字不得压住封口、折边、开口、按键或功能结构。商业场景不添加悬浮广告标题或说明卡，只呈现产品本体。
不要默认极简、高端、克制、低饱和、留白或编辑感；严格执行本方向自己的视觉性格、配色、图形、字体、表面工艺、场景和构图。水波、模特、浴室与透明材质仅在本方向明确且符合产品逻辑时使用。
${variation?`变体要求：${variation}。`:""} 最终为 9:16 竖版完整构图，严格上 60% 场景、下 40% 结构展示；整件产品和结构视图不得裁切；不要左右分栏、斜切、嵌入视图、乱码、灰色信息块、白色说明卡、悬浮标签、UI 面板、水印、设计过程稿或独立技术标注。`;
}
export function buildPackagingTexturePrompt(style:string,palette:string[],variation?:string){return `Seamless premium packaging background texture and decorative pattern. Style: ${style}. Palette: ${palette.join(", ")}. ${variation||""} Subtle, restrained, suitable behind accurate typography, large clean areas, flat front-facing texture, no box mockup, no product, no text, no letters, no symbols, no watermark.`;}
const marketingPrompts:Record<ImageType,(params:MarketingImageParams,index:number)=>string>={
 main_image:(p,i)=>`E-commerce hero background, pure white studio, premium cosmetic product and packaging display area, soft shadow, clean centered composition option ${i+1}, no text, no letters, no watermark.`,
 scene_image:(p,i)=>`Premium skincare lifestyle scene inspired by ${p.finalCopy.fields.find(f=>f.key==="usage_desc")?.content||"daily vanity and bathroom ritual"}. Elegant vanity or bathroom setting, natural soft light, product placement area, option ${i+1}, no text, no letters, no watermark.`,
 detail_selling_point:(p,i)=>`Premium skincare detail-page background with product pedestal and generous blank editorial layout area for programmatic benefit copy, palette ${p.finalProductDesign.cmf.colorScheme.join(", ")}, option ${i+1}, no text, no letters, no watermark.`,
 multi_angle:(p,i)=>`Commercial studio background for multiple-angle cosmetic product presentation, subtle turntable, controlled lighting, clean negative space, option ${i+1}, no text, no letters, no watermark.`,
 packaging_shot:(p,i)=>`Premium packaging photography background, rigid box presentation, front back and side display staging, realistic soft shadows, palette ${p.finalPackaging.palette.join(", ")}, option ${i+1}, no text, no letters, no watermark.`,
};
export const buildMarketingPrompt=(params:MarketingImageParams,type:ImageType,index:number)=>marketingPrompts[type](params,index);
