"use client";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { imageTypeMeta, marketingImageGenerator } from "@/services/marketing-image-generator";
import { imageTypes, type ImageType, type MarketingImage } from "@/types/marketing-image";
import { useDesignBrief } from "./design-brief-provider";
import { useAiUsageCount } from "./use-ai-usage-count";

const downloadData=(url:string,name:string)=>{const source=decodeURIComponent(url.slice(url.indexOf(",")+1));const objectUrl=URL.createObjectURL(new Blob([source],{type:"image/svg+xml"}));const a=document.createElement("a");a.href=objectUrl;a.download=`${name}.svg`;document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(objectUrl),1000);};
export function MarketingImagePage(){
 const aiUsageCount=useAiUsageCount("marketing");
 const router=useRouter(); const {hydrated,brief,completedSteps,logoProject,copyProject,productDesign,packagingProject,marketingImages,updateMarketingImages,completeStep}=useDesignBrief();
 const [generating,setGenerating]=useState(false); const [regenerating,setRegenerating]=useState<string>(); const [notice,setNotice]=useState("");
 const logo=logoProject.candidates.find(x=>x.id===logoProject.finalLogoId),copy=copyProject.finalPackage,product=productDesign.candidates.find(x=>x.id===productDesign.finalDesignId),packaging=packagingProject.finalDesign?.candidate;
 const groups=useMemo(()=>imageTypes.map(type=>({type,items:marketingImages.images.filter(image=>image.type===type)})).filter(group=>group.items.length),[marketingImages.images]);
 const toggle=(type:ImageType)=>updateMarketingImages(current=>({...current,selectedTypes:current.selectedTypes.includes(type)?current.selectedTypes.filter(x=>x!==type):[...current.selectedTypes,type]}));
 const generate=async()=>{if(!logo||!copy||!product||!packaging||!marketingImages.selectedTypes.length||generating)return;setGenerating(true);setNotice("");try{const images=await marketingImageGenerator.generate({finalLogo:{imageUrl:logo.imageUrl},finalCopy:copy,finalProductDesign:product,finalPackaging:packaging,imageTypes:marketingImages.selectedTypes,quantities:marketingImages.quantities});updateMarketingImages(current=>({...current,images,generationRound:current.generationRound+1}));completeStep(6);setNotice(`已生成 ${images.length} 张电商物料图`);}catch(error){setNotice(`生成失败：${error instanceof Error?error.message:"服务返回未知错误"}`);}finally{setGenerating(false)}};
 const regenerate=async(image:MarketingImage)=>{if(!logo||!copy||!product||!packaging||regenerating)return;setRegenerating(image.id);try{const [next]=await marketingImageGenerator.generate({finalLogo:{imageUrl:logo.imageUrl},finalCopy:copy,finalProductDesign:product,finalPackaging:packaging,imageTypes:[image.type],quantities:{[image.type]:1}});if(!next)throw new Error("服务未返回图片");updateMarketingImages(current=>({...current,images:current.images.map(item=>item.id===image.id?next:item)}));setNotice(`已重新生成「${image.title}」`);}catch(error){setNotice(`重新生成失败：${error instanceof Error?error.message:"服务返回未知错误"}`);}finally{setRegenerating(undefined)}};
 if(!hydrated)return <div className="form-loading"><span/><p>正在载入图片生成项目…</p></div>;
 if(!completedSteps.includes(5)||!logo||!copy||!product||!packaging)return <div className="placeholder-page"><span className="eyebrow">STEP 6 / 7</span><h1>请先完成外包装设计</h1><p>物料图生成需要读取 Logo、文案、产品与包装定稿。</p><button className="primary-button" onClick={()=>router.push("/workflow/5")}>返回第 5 步</button></div>;
 return <><div className="page-heading marketing-heading"><div><span className="eyebrow">STEP 6 / 7</span><h1>图片生成</h1><p>按渠道用途批量组合定稿资产，快速产出完整电商物料图。</p></div><span className="mock-badge">生成调用 {aiUsageCount} 次</span></div>
 <section className="image-input-card"><div className="logo-section-title"><div><span>01</span><div><h2>选择物料类型</h2><p>默认全选，每类可生成 2–4 张不同构图</p></div></div><b>{marketingImages.selectedTypes.length}/5</b></div><div className="image-type-grid">{imageTypes.map(type=>{const selected=marketingImages.selectedTypes.includes(type);const meta=imageTypeMeta[type];return <article className={selected?"selected":""} key={type}><button className="type-toggle" onClick={()=>toggle(type)}><span>{selected?"✓":""}</span><div><h3>{meta.label}</h3><p>{meta.description}</p></div></button><label>生成数量<select value={marketingImages.quantities[type]} onChange={e=>updateMarketingImages(current=>({...current,quantities:{...current.quantities,[type]:Number(e.target.value)}}))} disabled={!selected}><option value="2">2 张</option><option value="3">3 张</option><option value="4">4 张</option></select></label></article>})}</div><div className="image-generate-row"><span>{marketingImages.generationRound?`已完成 ${marketingImages.generationRound} 批 · 当前 ${marketingImages.images.length} 张`:`预计生成 ${marketingImages.selectedTypes.reduce((sum,type)=>sum+marketingImages.quantities[type],0)} 张`}</span><button className="primary-button" disabled={!marketingImages.selectedTypes.length||generating} onClick={()=>void generate()}>{generating?"正在批量生成…":marketingImages.images.length?"↻ 换一批":"✦ 生成物料图"}</button></div></section>
 <section className="marketing-results"><div className="logo-section-title"><div><span>02</span><div><h2>物料图结果</h2><p>按用途分组，可单张重生成或下载 SVG</p></div></div>{notice&&<span className="generation-notice">{notice}</span>}</div>{generating&&!marketingImages.images.length?<div className="marketing-loading">正在组合产品、包装与定稿文案…</div>:groups.length?groups.map(group=><div className="marketing-group" key={group.type}><div className="product-group-head"><strong>{imageTypeMeta[group.type].label}</strong><i/><span>{group.items.length} 张</span></div><div className="marketing-grid">{group.items.map(image=><article className="marketing-card" key={image.id}><div><img src={image.imageUrl} alt={image.title}/><span>{imageTypeMeta[image.type].label}</span></div><section><h3>{image.title}</h3>{image.copyUsed.length?<p>文案溯源：{image.copyUsed.join(" / ")}</p>:<p>使用视觉资产，无额外文案</p>}<div><button disabled={regenerating===image.id} onClick={()=>void regenerate(image)}>{regenerating===image.id?"生成中…":"↻ 重新生成"}</button><button onClick={()=>downloadData(image.imageUrl,image.title)}>↓ 下载 SVG</button></div></section></article>)}</div></div>):<div className="product-empty"><span>▧</span><p>尚未生成物料图</p><small>选择上方物料类型并开始批量生成。</small></div>}</section>
 {marketingImages.images.length>0&&<div className="page-actions"><span className="save-hint visible">✓ 全部物料已自动保存</span><button className="secondary-button" onClick={()=>marketingImages.images.forEach((image,index)=>window.setTimeout(()=>downloadData(image.imageUrl,image.title),index*120))}>批量下载 SVG</button><button className="primary-button" onClick={()=>router.push("/workflow/7")}>进入质检与交付 →</button></div>}</>;
}
