"use client";

import { useState } from "react";
import Link from "next/link";
import { BoxIcon } from "./icons";
import { boxTypes,checkBoxDimensions,rankBoxTypes } from "@/services/packaging-generator";
import { containerCostLabel,containerPainResponses,containerTypes,rankContainerTypes } from "@/services/container-library";
import { useDesignBrief } from "./design-brief-provider";

export function StructureAssetsPage(){
  const {brief,productDesign,updateProductDesign}=useDesignBrief();
  const [category,setCategory]=useState<"container"|"box">("container");
  const rankedBoxes=rankBoxTypes(brief),projectStructures=[...(productDesign.customContainers||[]),...(productDesign.aiRecommendedContainers||[])],rankedContainers=[...projectStructures,...rankContainerTypes(brief)].filter((item,index,array)=>array.findIndex(other=>other.id===item.id)===index);
  const finalProduct=productDesign.candidates.find(item=>item.id===productDesign.finalDesignId);
  const chooseContainer=(id:string)=>{const container=rankedContainers.find(item=>item.id===id);if(!container)return;updateProductDesign(current=>({...current,selectedContainerTypeId:id,selectedVolume:container.volumeOptions[0],structureConfirmed:false}))};
  return <div className="app-shell assets-shell"><aside className="sidebar"><div className="logo"><BoxIcon/><span>PackPilot</span></div><div className="workspace-label">工作空间</div><nav className="side-nav"><Link className="side-link" href="/workflow/4"><span>▦</span>项目</Link><Link className="side-link" href="/brand-assets"><span>◇</span>品牌资产库</Link><Link className="side-link active" href="/structure-assets"><span>⌑</span>结构资产库<em>{boxTypes.length+containerTypes.length}</em></Link><button disabled><span>▤</span>模板<em>即将推出</em></button><button disabled><span>⇧</span>导出<em>即将推出</em></button></nav><div className="sidebar-foot"><span className="avatar">P</span><div><strong>包装设计智能体</strong><small>模块 B · 工作台</small></div></div></aside><main className="main-area"><header className="topbar"><div><span className="crumb">资产</span><span className="slash">/</span><strong>结构资产库</strong></div><Link className="back-project" href={category==="container"?"/workflow/4":"/workflow/5"}>← 返回{category==="container"?"产品图设计":"外包装设计"}</Link></header><div className="assets-page"><div className="page-heading"><div><span className="eyebrow">STRUCTURE LIBRARY</span><h1>结构资产库</h1><p>统一管理内包材器形与外包装盒型结构。</p></div><span className="asset-count">{containerTypes.length} 种器形 · {boxTypes.length} 种盒型</span></div><div className="structure-category-tabs"><button className={category==="container"?"active":""} onClick={()=>setCategory("container")}><span>内包材</span><strong>器形</strong><em>{containerTypes.length}</em></button><button className={category==="box"?"active":""} onClick={()=>setCategory("box")}><span>外包装</span><strong>盒型</strong><em>{boxTypes.length}</em></button></div>
  {category==="container"?<><div className="asset-section-heading"><div><h2>产品形态与载体库</h2><p>{projectStructures.length?`包含 ${projectStructures.length} 个当前项目的 AI 建议或自定义结构。`:"按当前品类推荐排序，也可在第 4 步添加 AI 建议或自定义结构。"}</p></div></div><div className="structure-grid">{rankedContainers.map((container,index)=>{const responses=containerPainResponses(container,brief);return <article className="structure-card container-asset-card" key={container.id}><div className="structure-images"><img src={container.sketchUrl} alt={`${container.name}结构示意`}/>{container.source==="ai"?<span>AI 建议</span>:container.source==="upload"?<span>上传参考</span>:container.source==="manual"?<span>手动创建</span>:index<3&&<span>当前项目推荐 {index+1}</span>}</div><div><div className="structure-title"><h2>{container.name}</h2><em>{containerCostLabel(container.costLevel)}成本</em></div><p>{container.description||`${container.dispensingType}，适用于 ${container.suitableCategories.slice(0,4).join("、")}。`}</p><dl><div><dt>规格/尺寸</dt><dd>{container.volumeOptions.join(" · ")}</dd></div><div><dt>常见材质</dt><dd>{container.materialOptions.join(" · ")}</dd></div></dl>{responses.map(response=><span className="fit" key={response}>↗ 可回应痛点：{response}</span>)}{container.engineeringVerificationRequired&&<span className="mismatch">! 生产前需工程验证</span>}<Link href="/workflow/4" onClick={()=>chooseContainer(container.id)}>选用并确认 →</Link></div></article>})}</div></>:<><div className="asset-section-heading"><div><h2>盒型库</h2><p>按当前品类与价格带推荐，尺寸匹配读取定稿器形容量。</p></div></div><div className="structure-grid">{rankedBoxes.map((box,index)=>{const fit=checkBoxDimensions(brief,box,finalProduct?.containerType);return <article className="structure-card" key={box.id}><div className="structure-images"><img src={box.structureImageUrl} alt={`${box.name}结构示意`}/><img src={box.dielineImageUrl} alt={`${box.name}刀版示意`}/>{index<3&&<span>当前项目推荐 {index+1}</span>}</div><div><div className="structure-title"><h2>{box.name}</h2><em>{box.costLabel}成本</em></div><p>{box.description}</p><dl><div><dt>适用品类</dt><dd>{box.suitableCategories.join(" · ")}</dd></div><div><dt>参考尺寸</dt><dd>{box.referenceDimensionsLabel}</dd></div></dl><span className={fit.fits?"fit":"mismatch"}>{fit.fits?"✓":"!"} {fit.message}</span><Link href="/workflow/5">选用此结构 →</Link></div></article>})}</div></>}</div></main></div>;
}
