import { copyFieldKeys, copyFieldLabels, type CopyField, type CopyPackage } from "../types/copy.ts";
import { prohibitedAdvertisingTerms } from "../services/prompts/copy-prompts.ts";
function cleanJson(text:string){return text.trim().replace(/^```json\s*/i,"").replace(/```$/i,"").trim();}
export function validatePackages(text:string,validInsightIds:string[],requiredPainIds:string[],baseCopyId?:string,allowPartial=false):CopyPackage[]{
 const parsed=JSON.parse(cleanJson(text)) as {packages?:unknown[]}; if(!Array.isArray(parsed.packages)||(allowPartial?parsed.packages.length<1:parsed.packages.length!==3))throw new Error(allowPartial?"未返回文案方案":"必须返回三套文案");
 const packages=(allowPartial?parsed.packages.slice(0,1):parsed.packages).map((raw,index)=>{const item=raw as Partial<CopyPackage>;if(!Array.isArray(item.fields))throw new Error("文案字段缺失");const byKey=new Map(item.fields.map(f=>[f.key,f]));const fields=copyFieldKeys.map(key=>{const source=byKey.get(key) as CopyField|undefined;if(!source?.content&&!allowPartial)throw new Error(`缺少 ${key}`);const content=String(source?.content||"").trim();if(prohibitedAdvertisingTerms.some(term=>content.includes(term)))throw new Error("包含广告法风险词");if(/经测试|实验室|斑贴测试|临床|研究表明|纯度|≥|\d+\s*%|\d+\s*周/.test(content))throw new Error("包含未提供的实验、浓度或周期数据");if(!allowPartial&&key==="main_slogan"&&[...content.replace(/[，。！？、,.!?\s]/g,"")].length>12)throw new Error("主标语超过12字");const linked=source?.linkedInsightId&&validInsightIds.includes(source.linkedInsightId)?source.linkedInsightId:undefined;return{key,label:copyFieldLabels[key],content,...(linked?{linkedInsightId:linked}:{})};});const sourceInsightIds=[...new Set([...(item.sourceInsightIds||[]),...fields.flatMap(f=>f.linkedInsightId?[f.linkedInsightId]:[])])].filter(id=>validInsightIds.includes(id));return{id:`copy-ai-${Date.now()}-${index}`,directionName:String(item.directionName||(allowPartial?"当前视觉方案":undefined)||["理性成分风","情绪共鸣风","简洁高端风"][index]),toneTags:Array.isArray(item.toneTags)?item.toneTags.map(String).slice(0,5):[],fields,sourceInsightIds,...(baseCopyId?{parentId:baseCopyId}:{}),round:1};});
 if(!allowPartial&&requiredPainIds.some(id=>!packages.some(item=>item.fields.some(field=>field.linkedInsightId===id))))throw new Error("存在未被三套文案共同覆盖的痛点 insight id");
 return packages;
}
